# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - /var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    ports:
      - "8001:5432"
  backend:
    build: ../pong-backend/
    ports:
      - "3000:3000"
      - "8080:8080"
    environment: 
      - API_UID=${API_UID}
      - API_SECRET=${API_SECRET}
      - APP_SECRET=1234
      - DB_HOST=database
      - DB_PORT=5432
  front:
    build: ../front-typescript/
    ports:
      - "3001:3000"
    environment: 
      - REACT_APP_API_UID=${API_UID}